---
title: "538 wip1"
author: "Ole Fechner, Johannes Kopf"
date: "25 November 2018"
output: pdf_document
---

https://golovchenko.github.io/tutorials/snatrolls.html

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(dplyr)
library(readr)
library(knitr)
```

```{r, inlcude=F}
## setting working directory and loading the data.
tweets1 <- read.csv("Raw Data/IRAhandle_tweets_1.csv", stringsAsFactors = F, sep = ",")
tweets2 <- read.csv("Raw Data/IRAhandle_tweets_2.csv", stringsAsFactors = F, sep = ",")
tweets3 <- read.csv("Raw Data/IRAhandle_tweets_3.csv", stringsAsFactors = F, sep = ",")
tweets4 <- read.csv("Raw Data/IRAhandle_tweets_4.csv", stringsAsFactors = F, sep = ",")
tweets5 <- read.csv("Raw Data/IRAhandle_tweets_5.csv", stringsAsFactors = F, sep = ",")
tweets6 <- read.csv("Raw Data/IRAhandle_tweets_6.csv", stringsAsFactors = F, sep = ",")
tweets7 <- read.csv("Raw Data/IRAhandle_tweets_7.csv", stringsAsFactors = F, sep = ",")
tweets8 <- read.csv("Raw Data/IRAhandle_tweets_8.csv", stringsAsFactors = F, sep = ",")
tweets9 <- read.csv("Raw Data/IRAhandle_tweets_9.csv", stringsAsFactors = F, sep = ",")
tweets10 <- read.csv("Raw Data/IRAhandle_tweets_10.csv", stringsAsFactors = F, sep = ",")
tweets11 <- read.csv("Raw Data/IRAhandle_tweets_11.csv", stringsAsFactors = F, sep = ",")
tweets12 <- read.csv("Raw Data/IRAhandle_tweets_12.csv", stringsAsFactors = F, sep = ",")
tweets13 <- read.csv("Raw Data/IRAhandle_tweets_13.csv", stringsAsFactors = F, sep = ",")
```

```{r, inlcude=F}
## merging the 13 different datasets
tweets <- rbind(tweets1, tweets2, tweets3 , tweets4, tweets5, tweets6, tweets7, tweets8, tweets9,tweets10, tweets11, tweets12, tweets13)
```

```{r, echo=F}
## checking the number of unique twitter handles in the dataset (problem: handles can be changed -> one individual can be counted several times. though, this also applies for multiple accounts per user.) 
print(paste("Read ", length(tweets$content), " tweets", sep="", " by ", length(unique(tweets$author)), " unique Twitter handles."))
```

```{r, include=F}
## selecting only the retweets
rts <- grep("^rt @[a-z0-9_]{1,15}", tolower(tweets$content), perl=T, value=T)

## extracting handle names for the senders (those who retweet)
rt.sender <- tolower(as.character(tweets$author[grep("^rt @[a-z0-9_]{1,15}", tolower(tweets$content), perl=T)]))

## extracting handle names for the recievers (those who are being retweeted)
rt.receiver<- tolower(regmatches(rts, regexpr("@(?U).*:", rts)))
rt.receiver <- (gsub(":", "", rt.receiver)) ## removing ":"
rt.receiver <- (gsub("@", "", rt.receiver)) ## removing "@"

## Registering empty entries as missing
rt.sender[rt.sender==""] <- "<NA>"
rt.receiver[rt.receiver==""] <- "<NA>"

## a large proportion of this code is from <https://www.r-bloggers.com/generating-graphs-of-retweets-and-messages-on-twitter-using-r-and-gephi/> 
```

```{r, include=F}
## storing reciever and sender handle names in one dataframe and removing duplicates
handle.all <- unique(as.data.frame(c(rt.sender, rt.receiver))) 
## renaming the handle names variable
handle.all <- handle.all %>% rename(handle = "c(rt.sender, rt.receiver)")
```

```{r, include=F}
## importing handle names from the official list release in congress
trolls_official <-  read.csv("http://golovchenko.github.io/data/trollhandles.txt", stringsAsFactors = F)

## merging the complete list of official troll handle names with the ones in NBC data
tweets <- tweets %>% rename(handle = author) #renaming handle name variable
handles <- tweets %>% select(handle) #selecting only the handles from the data
handles <- rbind(trolls_official, handles)
handles <- tolower()
handles.u <- unique(handles) ## removing duplicates
handles.u$troll <- "troll" ## assigning all of these users a trolls

## matching trolls with the complete set of handle names in the retweet network
nodes <- right_join(handles.u, handle.all)
nodes <- replace(nodes, is.na(nodes), "non-troll") ## now we have a variable indicating wether a user is a troll
```

```{r, inlcude=F}
## Attention: Damit der n?chste Code Chunk nach diesem funktioniert, m?ssen rt.sender und rt.receiver auf gleich L?nge gebracht werden. Dazu werden hier die letzten 25 Reihen in rt.sender entfert.

rt.receiver.df <- as.data.frame(rt.receiver)
rt.sender.df <- as.data.frame(rt.sender) 

rt.sender.df <- rt.sender.df[-c(10612:10636), ]
rt.sender.df <- as.data.frame(rt.sender.df) 
```



```{r, include=F}
## Creating a data frame from the sender-receiver objects
rts.df <- data.frame(rt.sender.df, rt.receiver.df)
## creating the retweetnetwork based on the sender-receiver df and the node attributes (troll/non-troll)
rts.g <- graph.data.frame(rts.df, directed=T, vertices = nodes)
## removing self-ties
rts.g <-simplify(rts.g, remove.loops = T, remove.multiple = F)
```


```{r, include=F}
## creating the retweetnetwork based on the sender-receiver df and the node attributes (troll/non-troll)
rts.g <- graph.data.frame(rts.df, directed=T, vertices = nodes)
## removing self-ties
rts.g <- simplify(rts.g, remove.loops = T, remove.multiple = F)
```

```{r, include=F}
## removing multiple edges between users
g <- simplify(rts.g, remove.multiple = T, remove.loops = T)
## creating a data frame with weighted and unweighted degree centrality for each profile
df <- data.frame(name =V(g)$name,
                 troll= V(g)$troll,indegree=degree(g,mode='in'),
                 indegree_weighted = degree(rts.g, mode ="in"),
                 outdegree=degree(g,mode='out'),
                 outdegree_weighted = degree(rts.g, mode = "out"))
## ranking users by indegree
rank.indegree <- df %>% select(name, troll, indegree,
                          indegree_weighted) %>% arrange(-indegree)
```