---
title: "wip1"
author: "Johannes Kopf"
date: "24 November 2018"
output: pdf_document
---

"If you publish using the data, please credit NBC News, link to this page, and let us know. Send questions and projects to ben.popken@nbcuni.com or @bpopken." NBC article

https://golovchenko.github.io/tutorials/snatrolls.html


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(dplyr)
library(readr)
library(knitr)
library(ggplot2)
library(stargazer)
```

```{r, include=F}
###Loading the NBC News dataset###
tweets <- read.csv("Raw Data/tweets.csv", stringsAsFactors = F, sep = ",")
```

```{r, inlcude=F}
## loading the 538 twitter dataset for comparison of account types
tweets1 <- read.csv("Raw Data/IRAhandle_tweets_1.csv", stringsAsFactors = F, sep = ",")
tweets2 <- read.csv("Raw Data/IRAhandle_tweets_2.csv", stringsAsFactors = F, sep = ",")
tweets3 <- read.csv("Raw Data/IRAhandle_tweets_3.csv", stringsAsFactors = F, sep = ",")
tweets4 <- read.csv("Raw Data/IRAhandle_tweets_4.csv", stringsAsFactors = F, sep = ",")
tweets5 <- read.csv("Raw Data/IRAhandle_tweets_5.csv", stringsAsFactors = F, sep = ",")
tweets6 <- read.csv("Raw Data/IRAhandle_tweets_6.csv", stringsAsFactors = F, sep = ",")
tweets7 <- read.csv("Raw Data/IRAhandle_tweets_7.csv", stringsAsFactors = F, sep = ",")
tweets8 <- read.csv("Raw Data/IRAhandle_tweets_8.csv", stringsAsFactors = F, sep = ",")
tweets9 <- read.csv("Raw Data/IRAhandle_tweets_9.csv", stringsAsFactors = F, sep = ",")
tweets10 <- read.csv("Raw Data/IRAhandle_tweets_10.csv", stringsAsFactors = F, sep = ",")
tweets11 <- read.csv("Raw Data/IRAhandle_tweets_11.csv", stringsAsFactors = F, sep = ",")
tweets12 <- read.csv("Raw Data/IRAhandle_tweets_12.csv", stringsAsFactors = F, sep = ",")
tweets13 <- read.csv("Raw Data/IRAhandle_tweets_13.csv", stringsAsFactors = F, sep = ",")
tweets_538 <- rbind(tweets1, tweets2, tweets3 , tweets4, tweets5, tweets6, tweets7, tweets8, tweets9,tweets10, tweets11, tweets12, tweets13) ## merging into one dataset
rm(tweets1, tweets2, tweets3 , tweets4, tweets5, tweets6, tweets7, tweets8, tweets9,tweets10, tweets11, tweets12, tweets13) ## removing for better oversight in environment
```

```{r, include=F}
## number of handles for which we have accounty types (right/left/...)
## extracting handle variable and account_type variabe and removing duplicates
myvars <- c("author", "account_category") 
account_category <- tweets_538[myvars] %>% unique()
## 2843

## making variable name identical
tweets <- tweets %>% rename(handle = user_key)
account_category <- account_category %>% rename(handle = author)

## adding account_type variable to the NBC dataset
account_category$handle <- tolower(account_category$handle)
tweets <- left_join(tweets, account_category)

## for how many tweeting troll handles is an account type available?
handles <- select(tweets, handle, account_category) %>% unique()
length(na.omit(handles$account_category)) / length(handles$handle)
## roughly for 98% available
```

```{r, include=F}
###Extracting the retweets out of the tweets text###

## Code by Yevgeniy Golovchenko: https://golovchenko.github.io/tutorials/snatrolls.html

## selecting only the retweets
rts <- grep("^rt @[a-z0-9_]{1,15}", tolower(tweets$text), perl=T, value=T)

## number of retweets in the dataset
rts.as.df <- as.data.frame(rts) %>% rename(text = rts)
## 147,428
length(rts.as.df$text) / length(tweets$handle)
## ~72% of all tweets in the NBC dataset are retweets

## extracting handle names for the senders (those who retweet)
rt.sender <- tolower(as.character(tweets$handle[grep("^rt @[a-z0-9_]{1,15}", tolower(tweets$text), perl = T)]))

## how many unique retweet senders?
rt.sender.df <- as.data.frame(rt.sender) %>% unique() %>% rename(handle = rt.sender)
length(rt.sender.df$handle)
## 333 trolls retweeted 147,428 times

## how many trolls have not retweeted anyone and therefore are not in the network
length(unique(tweets$handle)) - length(rt.sender.df$handle)
## 120 trolls only tweeted and did not retweet (but could be retweeted)

## extracting handle names for the recievers (those who are being retweeted)
rt.receiver <- tolower(regmatches(rts, regexpr("@(?U).*:", rts)))
rt.receiver <- (gsub(":", "", rt.receiver)) ## removing ":"
rt.receiver <- (gsub("@", "", rt.receiver)) ## removing "@"

## how many unique retweet receivers?
rt.receiver.df <- as.data.frame(rt.receiver) %>% unique() %>% rename(handle = rt.receiver)
length(rt.receiver.df$handle)
## 36,707 unique handles are being retweeted
## calculating the share of trolls later
```

```{r, include=F}
## storing reciever and sender handle names in one dataframe and removing duplicates
handles_all <- unique(as.data.frame(c(rt.sender, rt.receiver))) %>% rename(handle = "c(rt.sender, rt.receiver)")
## There are 36,889 unique handles in the retweet dataset
```

```{r}
## FIRST CALCULATIONS FOR DATA DESCRIPTION

length(handles_all$handle) - length(rt.receiver.df$handle) ## 182
## Number of unique handles increases by 182 when adding the senders. Therefore, there are 182 trolls in the data, who sent but did not receive retweets

(length(handles_all$handle) - length(rt.receiver.df$handle)) / length(rt.sender.df$handle)
## 55% of trolls, who are senders, were not themself retweeted (are no receivers)

length(rt.sender.df$handle) - (length(handles_all$handle) - length(rt.receiver.df$handle)) ## 151
## There are 151 trolls who retweeted others and were themselves retweeted. They are the only nodes in our data that are both senders and reveivers (that we know of).

(length(rt.sender.df$handle) - (length(handles_all$handle) - length(rt.receiver.df$handle))) / length(rt.sender.df$handle)
## ~45% of trolls who are senders are also receivers

length(rt.receiver.df$handle) - (length(rt.sender.df$handle) - (length(handles_all$handle) - length(rt.receiver.df$handle)))
## 36,556 handles receive a retweet, but do not send a retweet
```


```{r, include=F}
## importing handle names from the official list release in congress
trolls_official <-  read.csv("http://golovchenko.github.io/data/trollhandles.txt", stringsAsFactors = F)

trolls_official$handle <- tolower(trolls_official$handle)

## importing second (newer) list of handle names
trolls_official_new <- read.delim("Raw Data/ira_handles.txt", sep="")

trolls_official_new$handle <- tolower(trolls_official_new$handle)
## 3841

trolls <- rbind(trolls_official, trolls_official_new) %>% unique()
## together 3848 (+7 from old list)

## all troll handles in NBC dataset
handles <- tweets %>% select(handle) %>% unique() 
## 453

## merging the complete list of official troll handle names with the handle names in NBC data
handles_trolls <- rbind(trolls_official, trolls_official_new, handles) %>% unique() 
## 3848
## all of the tweeting handles in the NBC data are officially trolls
```

```{r, include=F}
### Merging the older NBC list of trolls, with the newer Linvill/Warren; adding "troll" and "non-troll" labels as attributes###

## how many trolls are in the overall dataset, either as senders or receivers?
trolls_official$troll <- "troll" ## assigning all of these users a troll
trolls$troll <- "troll"

## matching trolls with the complete set of handle names in the retweet network
nodes <- right_join(trolls, handles_all)
length(na.omit(nodes$troll)) 
## there are 404 trolls in the retweet network

length(na.omit(nodes$troll))-length(rt.sender.df$handle)
## There are 71 trolls who are retweeted, but do not tweet themselves

nodes <- replace(nodes, is.na(nodes), "non-troll") 
## now we have a variable indicating wether a user is a troll
nodes <- left_join(nodes, account_category)

troll_nodes <- filter(nodes, nodes$troll == "troll")
length(na.omit(troll_nodes$account_category))
## 379 handles are regarded as trolls by the 538 dataset
## 389 handles are regarded as trolls by the NBC dataset
## 10 'trolls' don't have a category

length(na.omit(troll_nodes$account_category))/length(troll_nodes$handle)
## 98% category available

length(nodes$troll[nodes$troll=="non-troll"])
##36485 non-trolls in the dataset
```

```{r, include=F}
### Adding follower count as node attribute ###

## loading the additional user data to extract followers count
followers <- read.csv("Raw Data/users.csv", stringsAsFactors = F, sep = ",")

followers <- select(followers, screen_name, followers_count)
followers$screen_name <- tolower(followers$screen_name)
followers <- followers %>% rename(handle = screen_name)
length(na.omit(followers$followers_count))
## there is a followers_count available for 383 trolls (not available for 70)

tweets <- left_join(tweets, followers)
nodes <- left_join(nodes, followers)

## turning all NAs for account_type into "Unknown" for regular user (=non-troll)
troll_nodes$account_category <- replace(troll_nodes$account_category, is.na(troll_nodes$account_category), "Unknown")
troll_nodes <- left_join(troll_nodes, followers)

## cleaning up the node dataframe
nodes <- left_join(nodes, troll_nodes, by ="handle")
nodes$account_category.y <- replace(nodes$account_category.y, is.na(nodes$account_category.y), "Non-Troll")
nodes$troll.y <- replace(nodes$troll.y, is.na(nodes$troll.y), "non-troll")
nodes <- select(nodes, handle, troll.y, account_category.y, followers_count.y) %>% rename(account_category = account_category.y)
nodes <- nodes %>% rename(troll = troll.y)
nodes <- nodes %>% rename(followers_count = followers_count.y)
```

```{r, include = F}
### Creating the graph ### (1)

## Creating a data frame from the sender-receiver objects
rts.df <- data.frame(rt.sender, rt.receiver)

## creating the retweet network based on the sender-receiver df and the node attributes: troll/nontroll, account_type, followers_count
rts.g <- graph.data.frame(rts.df, directed = T, vertices = nodes)
rts.g <- simplify(rts.g, remove.multiple = T)

## removing self-ties and multiple edges between users
g <- simplify(rts.g, remove.loops = T, remove.multiple = T)

## only removing self ties
rts.g <- simplify(rts.g, remove.loops = T, remove.multiple = F)

## creating an undirected graph object
g.undir <- as.undirected(g, mode = "collapse")
```

```{r, include = F}
### Subsetting the graph by removing non-trolls ###

## selecting nodes to exclude
exclude <- V(rts.g)[account_category == "Non-Troll"]

## excluding the nodes
g.troll <- delete.vertices(rts.g, exclude)

## creating an undirected subgraph
g.troll.undir <- as.undirected(g.troll, mode = "collapse")
```

```{r}
## COMMUNITY DETECTION

## running infomap community detection
infomap <- cluster_infomap(g, nb.trials = 10,
                          modularity = T)

## running modularity optimization community detection
modularity <- cluster_louvain(g.undir)

V(g)$modularity <- modularity$membership
V(g)$infomap <- infomap$membership

## creating a data frame with the communities
df.community <- data.frame(handle = V(g)$name, infomap = V(g)$infomap, modularity = V(g)$modularity)

## appending new attributes to dataframe
nodes <- left_join(nodes, df.community, by = "handle")
```

```{r, include=F}
## COMMUNITY DETECTION - FIGURE 1

## appending community variables to troll nodes df
troll_nodes <- left_join(troll_nodes, df.community, by = "handle")

## FIGURE 1
## reordering of the bars to represent descending troll count
positions <- c("LeftTroll", "NonEnglish", "RightTroll", "HashtagGamer", "NewsFeed", "Unknown", "Fearmonger")

## plot
png(filename = "figure1.png", width = 700, height = 480)
ggplot(troll_nodes, aes(x=account_category)) +
  geom_bar(aes(fill = as.character(modularity)), show.legend = F 
           ) + scale_x_discrete(limits = positions) + 
    ylab("Number of Trolls") +
  xlab("") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), legend.position="none")
dev.off()
```

```{r}
## ACCOUNT CATEGORIES & COMMUNITIES IN NUMBERS 

## Right community (Linvill/Warren)
## gives proportion of communities in account categories
## only important for community merging

## Right
right_troll_communities <- filter(nodes, account_category == "RightTroll")
comms <- unique(right_troll_communities$modularity)
for (com in comms){
  print(com)
  print(length(right_troll_communities$modularity[right_troll_communities$modularity==com])/length(right_troll_communities$modularity))
}

## Left
left_troll_communities <- filter(nodes, account_category == "LeftTroll")
comms <- unique(left_troll_communities$modularity)
for (com in comms){
  print(com)
  print(length(left_troll_communities$modularity[left_troll_communities$modularity==com])/length(left_troll_communities$modularity))
}

## Hastager
hashtag_troll_communities <- filter(nodes, account_category == "HashtagGamer")
comms <- unique(hashtag_troll_communities$modularity)
communities <- unique(troll_nodes$modularity)
for (com in comms){
  print(com)
  print(length(hashtag_troll_communities$modularity[hashtag_troll_communities$modularity==com])/length(hashtag_troll_communities$modularity))
}

## Non-English
nonenglish_troll_communities <- filter(nodes, account_category == "NonEnglish")
comms <- unique(nonenglish_troll_communities$modularity)
for (com in comms){
  print(length(nonenglish_troll_communities$modularity[nonenglish_troll_communities$modularity==com])/length(nonenglish_troll_communities$modularity))
}

## picking the biggest communitie(s) of each account category as the representative(s) for this group
## creating new categories from modularity + Linvill/Warren

troll_nodes$com <- troll_nodes$modularity

## numbers are taken from the investigation of biggest communities within account categories that was carried out above
## all small communities are not examined any further and therefore merged into "Other"
troll_nodes$com[troll_nodes$com == 4] <- "Left"
troll_nodes$com[troll_nodes$com == 10] <- "Right"
troll_nodes$com[troll_nodes$com == 8] <- "Right"
troll_nodes$com[troll_nodes$com == 6] <- "Hashtager"
troll_nodes$com[troll_nodes$com != "Left" & troll_nodes$com != "Right" & troll_nodes$com != "Hashtager"] <- "Other"

## appending newly determined communities to nodes
com.df <- select(troll_nodes, handle, com)
nodes <- left_join(nodes, com.df)
nodes$com[is.na(nodes$com)] <- "Non-Troll"


## recreating the retweetnetwork to include new communities
rts.g <- graph.data.frame(rts.df, directed=T, vertices = nodes)

## removing self-ties and multiple edges between users
g <- simplify(rts.g, remove.loops = T, remove.multiple = T)
rts.g <- simplify(rts.g, remove.loops = T, remove.multiple = F)

## creating an undirected graph object
g.undir <- as.undirected(g, mode = "collapse")
```

```{r}
## FIGURE 2
## account categories among new communities
positions2 <- c("Right", "Left", "Hashtager", "Other")

png(filename = "figure2.png", width = 700, height = 480)
figure2 <- ggplot(troll_nodes, aes(x=com)) +
  geom_bar(aes(fill = as.character(account_category)), show.legend=T 
           ) + scale_x_discrete(limits = positions2) + 
  xlab("Newly Determined Communities") +
  ylab("Number of Trolls") +
  theme(legend.title=element_blank())
figure2 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
dev.off()
```

```{r}
## ENTIRE CHUNK NOT IN TEXT
## distribution of modularity communities among new communities
## new right community
right_troll_communities <- filter(nodes, com == "Right")
comms <- unique(right_troll_communities$modularity)
print("new right communitiy:")
for (com in comms){
  print(com)
  print(length(right_troll_communities$modularity[right_troll_communities$modularity==com])/length(right_troll_communities$modularity))
}

## new "other" community
other_troll_communities <- filter(nodes, com == "Other")
comms <- unique(other_troll_communities$modularity)
print("new other communitiy:")
for (com in comms){
  print(com)
  print(length(other_troll_communities$modularity[other_troll_communities$modularity==com])/length(other_troll_communities$modularity))
}

```

```{r, include=F}
## as plot
positions2 <- c("Right", "Left", "Hashtager", "Other")

ggplot(troll_nodes, aes(x=com)) +
  geom_bar(aes(fill = as.character(modularity)), show.legend=F 
           ) + scale_x_discrete(limits = positions2) + 
  ggtitle("Distribution of Communities within Account Categories by Linvill/Warren (2018)") +
  xlab("Sythesis of Qualitative and Modularity Algorithm Communities") +
  ylab("Number of Trolls") +
  labs(caption = "Note: Color reflects distinct communities using modularity community detection following ...")
```

```{r, include=F}
## GRAPH DENSITY


## Creating a subgraph with trolls only
exclude <- V(g)[com == "Non-Troll"]
## excluding the nodes
g.troll <- delete.vertices(g, exclude)
## creating an undirected subgraph
g.troll.undir <- as.undirected(g.troll, mode = "collapse")


## entire graph, directed and undirected; not in paper
graph.density(g, loops = F)
## 0.00006
graph.density(g.undir, loops = F)
## 0.00012

## subgraph of trolls, directed and undirected
graph.density(g.troll, loops = F)
## 0.008
graph.density(g.troll.undir, loops = F)
## 0.015

## for subgraphs of communities

#### right troll
## right directed
exclude1 <- V(g.troll)[com != "Right"]
g.troll.right <- delete.vertices(g.troll, exclude1)
graph.density(g.troll.right, loops = F)
## 0.038

## right undirected
exclude2 <- V(g.troll.undir)[com != "Right"]
g.troll.right.undir <- delete.vertices(g.troll.undir, exclude2)
graph.density(g.troll.right.undir, loops = F)
## 0.074

#### left troll
## left directed
exclude3 <- V(g.troll)[com != "Left"]
g.troll.left <- delete.vertices(g.troll, exclude3)
graph.density(g.troll.left, loops = F)
## 0.006

## left undirected
exclude4 <- V(g.troll.undir)[com != "Left"]
g.troll.left.undir <- delete.vertices(g.troll.undir, exclude4)
graph.density(g.troll.left.undir, loops = F)
## 0.012

#### Hashtager
## hashtager directed
exclude5 <- V(g.troll)[com != "Hashtager"]
g.troll.hash <- delete.vertices(g.troll, exclude5)
graph.density(g.troll.hash, loops = F)
## 0.095

## hashtager undirected
exclude6 <- V(g.troll.undir)[com != "Hashtager"]
g.troll.hash.undir <- delete.vertices(g.troll.undir, exclude6)
graph.density(g.troll.hash.undir, loops = F)
## 0.177
```

```{r}
## FIGURE 3
## Graph density bar plot
commu <- c("Right", "Right Undirected", "Left", "Left Undirected","Hashtager", "Hashtager Undirected")
color <- c(1,1,2,2,3,3)
dens <- c(graph.density(g.troll.right, loops = F), graph.density(g.troll.right.undir, loops = F), graph.density(g.troll.left, loops = F), graph.density(g.troll.left.undir, loops = F), graph.density(g.troll.hash, loops = F), graph.density(g.troll.hash.undir, loops = F))


df.dens <- data.frame(com=commu, dens=dens, color=color)

png(filename = "figure3.png", width = 700, height = 480)
figure3 <- ggplot(df.dens, aes(commu, dens)) +
  geom_col(aes(fill=as.character(color))) +
  ylab("Graph Density") +
  xlab("")
figure3 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), legend.position="none")
dev.off()
```

```{r, include = F}
###COMPUTING k-cores###

## computing graph coreness undirected and incoreness
V(g)$kcore = graph.coreness(g)
V(g)$kincore = graph.coreness(g, mode = "in")


# storing a list of nodes that belong to k <=9 and kin <=3
exclude_k10 <- V(g)[kcore < 10]
exclude_kin4 <- V(g)[kincore < 4]

# removing these nodes in order to make a k-10-core and a kin-4-core
k10 <- delete.vertices(g, exclude_k10)
kin4 <- delete.vertices(g, exclude_kin4)

## appending coreness and incoreness to node dataframe
core.df <- data.frame(handle = V(g)$name, coreness = V(g)$kcore)
nodes <- left_join(nodes, core.df)

incore.df <- data.frame(handle = V(g)$name, incoreness = V(g)$kincore)
nodes <- left_join(nodes, incore.df)

# inspecting the graphobjects to see number of nodes and edges
summary(k10)
1257 / 36889
18214 / 147428
#3.4% of the nodes and 12.3% of the edges

summary(kin4)
1754 / 36889
11988 / 147428
#4.8% of the nodes and 8.1% of the edges
```

```{r, include = F}
## DEGREE

## Creating degree df
df_degree <- data.frame(handle = V(g)$name,
                 indegree = degree(g,mode='in'),
                 indegree_weighted = degree(rts.g, mode ="in"),
                 outdegree = degree(g,mode='out'),
                 outdegree_weighted = degree(rts.g, mode = "out"))
nodes <- left_join(nodes, df_degree)
troll_nodes <- left_join(troll_nodes, df_degree)


## OUTDEGREE
rank.outdegree <- nodes %>% select(handle, com, account_category, followers_count, 
                                   outdegree, outdegree_weighted) %>% arrange(-outdegree)
rank.outdegree.w <- nodes %>% select(handle, com, account_category, followers_count, 
                                   outdegree, outdegree_weighted) %>% arrange(-outdegree_weighted)

## to investigate in R
kable(rank.outdegree[1:10,], caption = "Top 10 users ranked by outdegree")
kable(rank.outdegree.w[1:10,], caption = "Top 10 users ranked by weighted outdegree")

outdegree_table <- rank.outdegree[1:10,]
w_outdegree_table <- rank.outdegree.w[1:10,]

outdegree_table <- outdegree_table %>% rename(User = handle, Community = com, Category = account_category,
                                              Followers = followers_count, Outdegree = outdegree,
                                              Outdegree_Weighted = outdegree_weighted)

w_outdegree_table <- w_outdegree_table %>% rename(User = handle, Community = com, 
                                                  Category = account_category,
                                                  Followers = followers_count, Outdegree = outdegree,
                                                  Outdegree_Weighted = outdegree_weighted)

stargazer(outdegree_table, summary=F, align=F, title="Top 10 Users ranked by Outdegree", rownames=F, label = "tab:out")
stargazer(w_outdegree_table, summary=F, align=F, title="Top 10 Users ranked by Weighted Outdegree", rownames=F, label = "tab:wout")


## INDEGREE

rank.indegree <- nodes %>% select(handle, com, account_category,
                                   indegree, indegree_weighted) %>% arrange(-indegree)
rank.indegree.w <- nodes %>% select(handle, com, account_category,
                                   indegree, indegree_weighted) %>% arrange(-indegree_weighted)

## to investigate in R
kable(rank.indegree[1:10,], caption = "Top 10 Users ranked by indegree")
kable(rank.indegree.w[1:10,], caption = "Top 10 Users ranked by weighted indegree")

indegree_table <- rank.indegree[1:10,]
w_indegree_table <- rank.indegree.w[1:10,]

indegree_table <- indegree_table %>% rename(User = handle, Community = com, Indegree = indegree, 
                                            Category = account_category,
                                              Indegree_Weighted = indegree_weighted)

w_indegree_table <- w_indegree_table %>% rename(User = handle, Community = com, Category = account_category,
                                                  Indegree = indegree,
                                                  Indegree_Weighted = indegree_weighted)

stargazer(indegree_table, summary=F, align=F, title="Top 10 Users ranked by Indegree", rownames=F, label = "tab:in")
stargazer(w_indegree_table, summary=F, align=F, title="Top 10 Users ranked by Weighted Indegree", rownames=F, label = "tab:win")
```

```{r}
## BOX PLOT
ggplot(troll_nodes, aes(x = outdegree, y = indegree)) +
  geom_point(aes(color=com)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), legend.position="right", legend.background = element_blank()) + xlab("Outdegree") + ylab("Indegree")
```

```{r}
core_nodes <- filter(nodes, coreness >= 10) %>% arrange(-outdegree)
incore_nodes <- filter(nodes, incoreness >= 4) %>% arrange(-outdegree)

core_nodes <- core_nodes[1:30,]
incore_nodes <- incore_nodes[1:30,]

png(filename = "k10_figure.png", width = 700, height = 480)
ggplot(core_nodes, aes(x = reorder(handle, -outdegree), y=outdegree)) +
  geom_col(aes(fill=com)) + theme(panel.grid.major = element_blank(), legend.title=element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), legend.position="right", legend.background = element_blank()) +
  theme(axis.text.x = element_text(angle=90)) + xlab("")
dev.off()
```


```{r, inlcude=F}
## GRAPHML FILE
write.graph(g, file="troll_network.graphml", format="graphml")
```

```{r, include=F}
## TABLE 1
## using numbers from calculations that can be seen in the chapter on data description
User <- c("Troll", "Non-Troll", "Total")
N <- c("404", "36,485", "36,889")
Senders <- c("333", "0", "333")
Receivers <- c("222", "36,485", "36,707")

table1 <- cbind(User, N, Senders, Receivers)

stargazer(table1, summary=F, align=F, title="User Statistics")
```

```{r, include=F}
## TABLE 2
## creating summary stats for trolls only

## first, vectors are created, which are later used as variables in the table

## Rownames
Category <- c("Right", "Left", "Hashtag Gamer", "Non-English", "Newsfeed", "Fearmonger", "Unknown", "Total")

## Number of Trolls
N <- c(length(troll_nodes$account_category[troll_nodes$account_category=="RightTroll"]), length(troll_nodes$account_category[troll_nodes$account_category=="LeftTroll"]), length(troll_nodes$account_category[troll_nodes$account_category=="HashtagGamer"]), length(troll_nodes$account_category[troll_nodes$account_category=="NonEnglish"]), length(troll_nodes$account_category[troll_nodes$account_category=="NewsFeed"]), length(troll_nodes$account_category[troll_nodes$account_category=="Fearmonger"]), length(troll_nodes$account_category[troll_nodes$account_category=="Unknown"]), "404")

## Sender Count
rt.sender.df <- left_join(rt.sender.df, account_category)
rt.sender.df$account_category <- replace(rt.sender.df$account_category, is.na(rt.sender.df$account_category), "Unknown")

Senders <- c(length(rt.sender.df$account_category[rt.sender.df$account_category=="RightTroll"]), length(rt.sender.df$account_category[rt.sender.df$account_category=="LeftTroll"]),              length(rt.sender.df$account_category[rt.sender.df$account_category=="HashtagGamer"]),
length(rt.sender.df$account_category[rt.sender.df$account_category=="NonEnglish"]),  length(rt.sender.df$account_category[rt.sender.df$account_category=="NewsFeed"]), length(rt.sender.df$account_category[rt.sender.df$account_category=="Fearmonger"]), length(rt.sender.df$account_category[rt.sender.df$account_category=="Unknown"]), "333")                    

rt.sender.df$sender <- "Sender"
troll_nodes <- left_join(troll_nodes, rt.sender.df)

## Receiver Count
rt.receiver.df$receiver <- "Receiver"
troll_nodes <- left_join(troll_nodes, rt.receiver.df)
receiver_count <- filter(troll_nodes, troll_nodes$receiver=="Receiver")

Receivers <- c(length(receiver_count$account_category[receiver_count$account_category=="RightTroll"]), length(receiver_count$account_category[receiver_count$account_category=="LeftTroll"]),              length(receiver_count$account_category[receiver_count$account_category=="HashtagGamer"]),
length(receiver_count$account_category[receiver_count$account_category=="NonEnglish"]),  length(receiver_count$account_category[receiver_count$account_category=="NewsFeed"]), length(receiver_count$account_category[receiver_count$account_category=="Fearmonger"]), length(receiver_count$account_category[receiver_count$account_category=="Unknown"]), "222")                                                          
## Followers

## creating sub-dataframes for each troll group
right_trolls <- filter(troll_nodes, troll_nodes$account_category=="RightTroll")
left_trolls <- filter(troll_nodes, troll_nodes$account_category=="LeftTroll")
hashtager <- filter(troll_nodes, troll_nodes$account_category=="HashtagGamer")
nonenglish <- filter(troll_nodes, troll_nodes$account_category=="NonEnglish")
newsfeed <- filter(troll_nodes, troll_nodes$account_category=="NewsFeed")
fearmonger <- filter(troll_nodes, troll_nodes$account_category=="Fearmonger")
unknown <- filter(troll_nodes, troll_nodes$account_category=="Unknown")

## calculating the rounded average while omitting NAs
Average_Followers <- c(round(mean(na.omit(right_trolls$followers_count), digits=0)), round(mean(na.omit(left_trolls$followers_count)), digits=0), round(mean(na.omit(hashtager$followers_count)), digits=0), round(mean(na.omit(nonenglish$followers_count)), digits=0), round(mean(na.omit(newsfeed$followers_count)), digits=0), 0, round(mean(na.omit(unknown$followers_count)), digits=0), 4476)

table2 <- cbind(Category, N, Senders, Receivers, Average_Followers)

stargazer(table2, summary=F, align=F, title="Troll Statistics")
```



#################################################
#################################################
From here on, other plots etc. are prepared

```{r}
plot(g,
     main="K Cores",
     vertex.size = 20,
     vertex.label = V(g)$Kcore,
     vertex.label.color = "black",
     vertex.label.cex = 1,
     vertex.color = "white")
```


>>>>>>> adfe9f5e2259ea4dd1057473520bb85f92a8ecfa
```{r, include=F}
## creating a data frame with weighted and unweighted degree centrality for each profile
df <- data.frame(name = V(g)$name,
                 troll = V(g)$troll,
                 account_category = V(g)$account_category,
                 indegree=degree(g, mode = 'in'),
                 indegree_weighted = degree(rts.g, mode = "in"),
                 outdegree = degree(g, mode= 'out'),
                 outdegree_weighted = degree(rts.g, mode = "out"))
```
